DROP DATABASE IF EXISTS murderdb;
CREATE DATABASE murderdb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

use murderdb;

CREATE TABLE murder (
    id INT(6) AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (id)
);

use testdb;

CREATE TABLE test (
    id INT(6) AUTO_INCREMENT NOT NULL,
    PRIMARY KEY (id)
);